### ISSUE TITLE
Editing groups

### ISSUE THREAD

**Issue by NixTS** [NixTS/movie-reviews-with-friends#12]
### Acceptance criteria

- "I can edit the groups title, tagline, description, picture."
- "I can delete my group, if i am the group admin/creator"

### Tasks

- [x] Create the function
- [x] Create the view
- [x] Create the form
- [x] Create the url pattern
- [x] Create the template
