### ISSUE TITLE
Navigation and footer

### ISSUE THREAD

**Issue by NixTS** [NixTS/movie-reviews-with-friends#15]
### Acceptance criteria

- "A navigation bar that is constantly displayed on top of the page."
- "A footer bar that is constantly displayed on the bottom of the page."
- "The navigation includes links to acces key features faster"

### Tasks

- [x] Create base.html
- [x] Create links and URLs
- [x] Create block content on each page
- [x] Create the styling
