### ISSUE TITLE
Editing reviews

### ISSUE THREAD

**Issue by NixTS** [NixTS/movie-reviews-with-friends#17]
### Acceptance criteria

- "I can edit my own reviews with full text editing functionality"

### Tasks

- [x] Create the view
- [x] Create the url pattern
- [x] Create the template
