### ISSUE TITLE
Error pages

### ISSUE THREAD

**Issue by NixTS** [NixTS/movie-reviews-with-friends#23]
### Acceptance criteria

- "Set up error 404 page not found page."
- "Set up access denied page."

### Tasks

- [ ] Create error404 Template
- [ ] Create error404 handling
- [ ] Create access denied template
- [ ] Create access denied handling
