### ISSUE TITLE
Secure access to CRUD features

### ISSUE THREAD

**Issue by NixTS** [NixTS/movie-reviews-with-friends#25]
### Acceptance criteria

- "Implement login required feature"
- "Implement checks if the user trying to access a certain feature is the correct user"

### Tasks

- [x] Create login required redirect
- [x] Create if statements to check for authorisation
- [x] Create access denied template
