### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by NixTS** [NixTS/movie-reviews-with-friends#26]
### Acceptance criteria

- "Create a homepage for not logged in users."
- "Create a homepage for logged in users showing the their groups:"

### Tasks

- [x] Create the view
- [x] Create the template
- [x] Create the url
