### ISSUE TITLE
Other users display

### ISSUE THREAD

**Issue by NixTS** [NixTS/movie-reviews-with-friends#27]
### Acceptance criteria

- "Display a list of users registered on this site."
- "Display user informations upon clicking on their profile."

### Tasks

- [x] Create the view
- [x] Create the template
- [x] Create the url
