### ISSUE TITLE
Add movies to my favorites

### ISSUE THREAD

**Issue by NixTS** [NixTS/movie-reviews-with-friends#6]
### Acceptance criteria

- "Adding a movie to my favorites should be done by clicking on a button with confirmation."
- "I can add as many movies as i want"

### Tasks

- [ ] Create the model
- [ ] Create the view
- [ ] Create the function
- [ ] Create the template
