### ISSUE TITLE
Create groups

### ISSUE THREAD

**Issue by NixTS** [NixTS/movie-reviews-with-friends#7]
### Acceptance criteria

- "Every user can create as many groups as one want."
- "I can set group title, tagline, description and a picture."

### Tasks

- [x] Create the model
- [x] Create the view
- [x] Create the the url pattern
- [x] Create the template
