### ISSUE TITLE
View all groups

### ISSUE THREAD

**Issue by NixTS** [NixTS/movie-reviews-with-friends#8]
### Acceptance criteria

- "I want to see group title, their group picture and the tagline."

### Tasks

- [x] Create the view
- [x] Create the url pattern
- [x] Create the template
