### ISSUE TITLE
Display a group

### ISSUE THREAD

**Issue by NixTS** [NixTS/movie-reviews-with-friends#9]
### Acceptance criteria

- "Clicking on a group opens the groups page."
- "I can see the groups title, picture, tagline, description and users in that group."

### Tasks

- [x] Create the view
- [x] Create the url pattern
- [x] Create the template
